[package]
name = "pax-engine"
version = "0.15.5"
authors = ["Zack Brown <zack@pax.dev>"]
edition = "2021"
license = "MIT OR Apache-2.0"
homepage = "https://pax.dev/"
repository = "https://www.github.com/paxproject/pax"
description = "Root import entry-point for using Pax in a Rust program"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pax-macro = {path="../pax-macro", version="0.15.5"}
pax-message = {path="../pax-message", version="0.15.5"}
pax-runtime = {path="../pax-runtime", version="0.15.5"}
pax-compiler = {path="../pax-compiler", optional=true, version="0.15.5"}
log = "0.4.20"

[features]
parser = ["dep:pax-compiler"]

