[package]
name = "pax-properties-coproduct"
version = "0.0.1"

authors = ["Zack Brown <zack@pax.rs>"]
edition = "2021"
license = "MIT OR Apache-2.0"
homepage = "https://www.pax.rs/"
repository = "https://www.github.com/pax-lang/pax"
description = "Static container for program-variable data structures and polymorphic components"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

pax-runtime-api = {path = "../../../pax-runtime-api", version="0.0.1"}
pax-example = { path="../.." }

#
#[patch.crates-io]
#pax-runtime-api= {path = "../pax-runtime-api"}