[package]
name = "pax-compiler"
version = "0.0.1"
authors = ["Zack Brown <zack@pax-lang.org>"]
edition = "2021"
license = "MIT OR Apache-2.0"
homepage = "https://www.pax-lang.org/"
repository = "https://www.github.com/pax-lang/pax"
description = "Compiler APIs for parsing and building Pax projects into application executables"

[features]
default = ["console_error_panic_hook", "cbor", "json", "messagepack"]
json = ["serde", "serde_json"]
messagepack = ["serde"]
cbor = ["serde"]

[lib]

[dependencies]
pax-message = {version = "0.0.1", path="../pax-message"}
pest = "2.4.1"
pest_derive = "2.4.1"
itertools = "0.10.5"
include_dir = {version = "0.7.2", features = ["glob"]}
serde_derive = "1"
toml_edit = "0.14.4"
lazy_static = "1.4.0"

tera = "1"
walkdir = "2.3.2"
rand = "0.8.4"

portpicker = "0.1.1"

serde = { version = "1", features=["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
wasm-bindgen = {version = "0.2.30", features=["serde-serialize"]}
console_error_panic_hook = { version = "0.1.6", optional = true }
futures = "0.3"

uuid = {version = "0.8", features = ["v4"] }
bincode = "1.3.3"




