[package]
name = "fireworks"
version = "0.15.4"
edition = "2021"
default-run = "run"

[dependencies]
pax-engine = { version = "0.15.4" }
pax-std = { version = "0.15.4" }
pax-compiler = { version = "0.15.4", optional = true }
pax-manifest = { version = "0.15.4" }
serde_json = {version = "1.0.95", optional = true}

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "parser"
path = "src/lib.rs"
required-features = ["parser"]

[[bin]]
name = "run"
path = "bin/run.rs"

[features]
parser = ["pax-std/parser", "pax-engine/parser", "dep:serde_json", "dep:pax-compiler"]
