[package]
name = "fireworks"
version = "0.10.10"
edition = "2021"
default-run = "run"

[dependencies]
pax-engine = { version = "0.15.4" , path = "../../../pax-engine" }
pax-std = { version = "0.15.4" , path = "../../../pax-std" }
pax-compiler = { version = "0.15.4", path = "../../../pax-compiler" }
pax-manifest = { version = "0.15.4" , path = "../../../pax-manifest" }
serde_json = {version = "1.0.95", optional = true}

[[bin]]
name = "run"
path = "bin/run.rs"

