[package]
name = "calculator"
version = "0.22.0"
edition = "2021"
default-run = "run"

[dependencies]
pax-engine = { version = "0.23.0", path="../../../pax-engine" }
pax-std = { version = "0.23.0", path="../../../pax-std" }

[lib]
crate-type = ["cdylib", "rlib"]
name = "paxcartridge"

[[bin]]
name = "parser"
path = "src/lib.rs"
required-features = ["parser"]

[[bin]]
name = "run"
path = "bin/run.rs"

[features]
parser = ["pax-std/parser"]
designtime = ["pax-engine/designtime"]
web = ["pax-engine/web"]
macos = ["pax-engine/macos"]
ios = ["pax-engine/ios"]

[profile.release]
lto = true
opt-level = "z"

[profile.dev.package."*"]
debug = false

[profile.dev]
opt-level = 2