[package]
name = "carbon-metaruntime"
version = "0.1.0"
authors = ["Zack Brown <zack@zpad.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
carbon = { path = "../carbon"}