[package]
name = "pax-runtime"
version = "0.15.5"
authors = ["Zack Brown <zack@pax.dev>"]
edition = "2021"
license = "MIT OR Apache-2.0"
homepage = "https://pax.dev/"
repository = "https://www.github.com/paxproject/pax"
description = "Core shared runtime and rendering engine for Pax"


[dependencies]
log = "0.4.20"
piet = "0.6.0"
piet-common = "0.6.0"
kurbo = "0.9.0"
serde = {version="1.0.196", features=["derive"]}
lazy_static = "1.4.0"
mut_static = "5.0.0"
pax-message = {path = "../pax-message", version="0.15.5"}
wasm-bindgen = {version = "0.2.92", features=["serde-serialize"]}
pax-manifest = {version="0.15.5", path = "../pax-manifest"}
pax-designtime = {version="0.15.5", path = "../pax-designtime", optional = true}
pax-runtime-api = {version="0.15.5", path = "../pax-runtime-api"}
cfg-if = "1.0.0"

[features]
designtime = ["pax-designtime"]