
[package]
name = "pax-std"
version = "0.0.1"
authors = ["Zack Brown <zack@pax.rs>"]
edition = "2021"
license = "MIT OR Apache-2.0"
homepage = "https://pax.rs/"
repository = "https://www.github.com/pax-lang/pax"
description = "Standard library for Pax, including layouts, drawing primitives, and form controls"


[package.metadata.pax]
primitives_crate = "./pax-std-primitives"

[dependencies]
piet = "0.6.0"
kurbo = "0.9.0"
pax = {package="pax-lang", path = "../pax-lang", features = ["parser"], version="0.0.1"}
pax-message = {path = "../pax-message", version="0.0.1"}
lazy_static = "1.4.0"
pax-compiler = {path="../pax-compiler", optional = true, version="0.0.1"}
serde_json = {version="1", optional = true}

[features]
parser = ["dep:pax-compiler", "dep:serde_json"]